[package]
name = "amqp-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
byteorder = "1.4.3"
log = "0.4.17"
env_logger = "0.9.3"
amqp_macros  = { path = "../amqp-macros" }
